spring:
  application:
    name: algovisual-api
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/algovisual}

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: never

app:
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:5173}
  jwt:
    secret: ${JWT_SECRET:SeMZOjXnflBCwbM26S8/HaF22vYzCneAfZQ6pG/UY1pvzb6kwERQbfgT8v1KtApMhRN1x0Lt2bxTpyF7prNCEA==}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}
